# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 01:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='B_Id')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Payment ID')),
                ('name', models.DateField(blank=True, default=datetime.date.today, verbose_name='Payment Date')),
                ('amount', models.PositiveIntegerField(blank=True, verbose_name='Amount')),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='B_Id_Payment', to='payments.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Service Name')),
                ('price', models.PositiveIntegerField(blank=True, verbose_name='Price')),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='B_Id_Service', to='payments.Contract')),
            ],
        ),
    ]
