# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='name',
            new_name='payment_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='id',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='service_name',
        ),
    ]
