# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 14:54
from __future__ import unicode_literals

import category.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('parent', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.FileField(null=True, upload_to=category.models.user_directory_path)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.CharField(default='No Description', max_length=150)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id', 'name', 'is_featured'),
            },
        ),
    ]
