# Generated by Django 2.1 on 2018-08-18 08:56

from django.db import migrations, models
import usermgmt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('parent', models.CharField(max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.FileField(null=True, upload_to=usermgmt.models.user_directory_path)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.BooleanField(default='No Description')),
            ],
        ),
    ]
