# Generated by Django 2.1 on 2018-08-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0002_auto_20180818_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='description',
            field=models.CharField(default='No Description', max_length=150),
        ),
    ]
